version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "@types/react-color"
